### PR TITLE
add query string to logged page view

### PR DESCRIPTION
**Pull request by justin-prather**

### CODE REVIEW

**Comment by leeDav** [comment]
I would also like this very much, and was about to raise a PR for exactly the same thing as the documentation for ReactGA also includes `window.location.search`.

Can this be merged, please, @sergiodxa?

**Comment by leeDav** [comment]
@sergiodxa, any update on this please?

**Comment by Emiliano-Bucci** [comment]
@sergiodxa Me too i'm waiting this pr; is it possible to merge it? I've tried to add this to the `prod.js` file but without success :/

**Comment by berkona** [comment]
@sergiodxa bump

**Comment by sergiodxa** [comment]
The Next.js team has an official plugin being developed, while plugin supports it's still in canary only, the way the plugin works it's simpler than next-ga and I recommend you to check it and do it manually in your project until it's stable.

Plugin link: https://github.com/zeit/next.js/tree/canary/packages/next-plugin-google-analytics

**Pull request closed without merging**
